//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class AssistedTeleopGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/AssistedTeleop";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public BuiltinInterfaces.DurationMsg time_allowance;

        public AssistedTeleopGoal()
        {
            this.time_allowance = new BuiltinInterfaces.DurationMsg();
        }

        public AssistedTeleopGoal(BuiltinInterfaces.DurationMsg time_allowance)
        {
            this.time_allowance = time_allowance;
        }

        public static AssistedTeleopGoal Deserialize(MessageDeserializer deserializer) => new AssistedTeleopGoal(deserializer);

        private AssistedTeleopGoal(MessageDeserializer deserializer)
        {
            this.time_allowance = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time_allowance);
        }

        public override string ToString()
        {
            return "AssistedTeleopGoal: " +
            "\ntime_allowance: " + time_allowance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
