//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class AssistedTeleopFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/AssistedTeleop";
        public override string RosMessageName => k_RosMessageName;

        // feedback
        public BuiltinInterfaces.DurationMsg current_teleop_duration;

        public AssistedTeleopFeedback()
        {
            this.current_teleop_duration = new BuiltinInterfaces.DurationMsg();
        }

        public AssistedTeleopFeedback(BuiltinInterfaces.DurationMsg current_teleop_duration)
        {
            this.current_teleop_duration = current_teleop_duration;
        }

        public static AssistedTeleopFeedback Deserialize(MessageDeserializer deserializer) => new AssistedTeleopFeedback(deserializer);

        private AssistedTeleopFeedback(MessageDeserializer deserializer)
        {
            this.current_teleop_duration = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_teleop_duration);
        }

        public override string ToString()
        {
            return "AssistedTeleopFeedback: " +
            "\ncurrent_teleop_duration: " + current_teleop_duration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
