//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class BackUpFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/BackUp";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition
        public float distance_traveled;

        public BackUpFeedback()
        {
            this.distance_traveled = 0.0f;
        }

        public BackUpFeedback(float distance_traveled)
        {
            this.distance_traveled = distance_traveled;
        }

        public static BackUpFeedback Deserialize(MessageDeserializer deserializer) => new BackUpFeedback(deserializer);

        private BackUpFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance_traveled);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.distance_traveled);
        }

        public override string ToString()
        {
            return "BackUpFeedback: " +
            "\ndistance_traveled: " + distance_traveled.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
