//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class BackUpGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/BackUp";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Geometry.PointMsg target;
        public float speed;
        public BuiltinInterfaces.DurationMsg time_allowance;

        public BackUpGoal()
        {
            this.target = new Geometry.PointMsg();
            this.speed = 0.0f;
            this.time_allowance = new BuiltinInterfaces.DurationMsg();
        }

        public BackUpGoal(Geometry.PointMsg target, float speed, BuiltinInterfaces.DurationMsg time_allowance)
        {
            this.target = target;
            this.speed = speed;
            this.time_allowance = time_allowance;
        }

        public static BackUpGoal Deserialize(MessageDeserializer deserializer) => new BackUpGoal(deserializer);

        private BackUpGoal(MessageDeserializer deserializer)
        {
            this.target = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.speed);
            this.time_allowance = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
            serializer.Write(this.speed);
            serializer.Write(this.time_allowance);
        }

        public override string ToString()
        {
            return "BackUpGoal: " +
            "\ntarget: " + target.ToString() +
            "\nspeed: " + speed.ToString() +
            "\ntime_allowance: " + time_allowance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
