//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputePathToPoseFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputePathToPose";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition

        public ComputePathToPoseFeedback()
        {
        }
        public static ComputePathToPoseFeedback Deserialize(MessageDeserializer deserializer) => new ComputePathToPoseFeedback(deserializer);

        private ComputePathToPoseFeedback(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "ComputePathToPoseFeedback: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
