//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputePathThroughPosesGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputePathThroughPoses";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Geometry.PoseStampedMsg[] goals;
        public Geometry.PoseStampedMsg start;
        public string planner_id;
        public bool use_start;
        //  If false, use current robot pose as path start, if true, use start above instead

        public ComputePathThroughPosesGoal()
        {
            this.goals = new Geometry.PoseStampedMsg[0];
            this.start = new Geometry.PoseStampedMsg();
            this.planner_id = "";
            this.use_start = false;
        }

        public ComputePathThroughPosesGoal(Geometry.PoseStampedMsg[] goals, Geometry.PoseStampedMsg start, string planner_id, bool use_start)
        {
            this.goals = goals;
            this.start = start;
            this.planner_id = planner_id;
            this.use_start = use_start;
        }

        public static ComputePathThroughPosesGoal Deserialize(MessageDeserializer deserializer) => new ComputePathThroughPosesGoal(deserializer);

        private ComputePathThroughPosesGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.goals, Geometry.PoseStampedMsg.Deserialize, deserializer.ReadLength());
            this.start = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.planner_id);
            deserializer.Read(out this.use_start);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.goals);
            serializer.Write(this.goals);
            serializer.Write(this.start);
            serializer.Write(this.planner_id);
            serializer.Write(this.use_start);
        }

        public override string ToString()
        {
            return "ComputePathThroughPosesGoal: " +
            "\ngoals: " + System.String.Join(", ", goals.ToList()) +
            "\nstart: " + start.ToString() +
            "\nplanner_id: " + planner_id.ToString() +
            "\nuse_start: " + use_start.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
