//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputeAndTrackRouteResult : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputeAndTrackRoute";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        //  Error codes
        public const ushort NONE = 0;
        public const ushort UNKNOWN = 400;
        public const ushort TF_ERROR = 401;
        public const ushort NO_VALID_GRAPH = 402;
        public const ushort INDETERMINANT_NODES_ON_GRAPH = 403;
        public const ushort TIMEOUT = 404;
        public const ushort NO_VALID_ROUTE = 405;
        public const ushort OPERATION_FAILED = 406;
        public const ushort INVALID_EDGE_SCORER_USE = 407;
        public BuiltinInterfaces.DurationMsg execution_duration;

        public ComputeAndTrackRouteResult()
        {
            this.execution_duration = new BuiltinInterfaces.DurationMsg();
        }

        public ComputeAndTrackRouteResult(BuiltinInterfaces.DurationMsg execution_duration)
        {
            this.execution_duration = execution_duration;
        }

        public static ComputeAndTrackRouteResult Deserialize(MessageDeserializer deserializer) => new ComputeAndTrackRouteResult(deserializer);

        private ComputeAndTrackRouteResult(MessageDeserializer deserializer)
        {
            this.execution_duration = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.execution_duration);
        }

        public override string ToString()
        {
            return "ComputeAndTrackRouteResult: " +
            "\nexecution_duration: " + execution_duration.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
