//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputePathThroughPosesResult : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputePathThroughPoses";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        public Nav.PathMsg path;
        public BuiltinInterfaces.DurationMsg planning_time;

        public ComputePathThroughPosesResult()
        {
            this.path = new Nav.PathMsg();
            this.planning_time = new BuiltinInterfaces.DurationMsg();
        }

        public ComputePathThroughPosesResult(Nav.PathMsg path, BuiltinInterfaces.DurationMsg planning_time)
        {
            this.path = path;
            this.planning_time = planning_time;
        }

        public static ComputePathThroughPosesResult Deserialize(MessageDeserializer deserializer) => new ComputePathThroughPosesResult(deserializer);

        private ComputePathThroughPosesResult(MessageDeserializer deserializer)
        {
            this.path = Nav.PathMsg.Deserialize(deserializer);
            this.planning_time = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.path);
            serializer.Write(this.planning_time);
        }

        public override string ToString()
        {
            return "ComputePathThroughPosesResult: " +
            "\npath: " + path.ToString() +
            "\nplanning_time: " + planning_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
