//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputeAndTrackRouteFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputeAndTrackRoute";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition
        public ushort last_node_id;
        public ushort next_node_id;
        public ushort current_edge_id;
        public RouteMsg route;
        public Nav.PathMsg path;
        public string[] operations_triggered;
        public bool rerouted;

        public ComputeAndTrackRouteFeedback()
        {
            this.last_node_id = 0;
            this.next_node_id = 0;
            this.current_edge_id = 0;
            this.route = new RouteMsg();
            this.path = new Nav.PathMsg();
            this.operations_triggered = new string[0];
            this.rerouted = false;
        }

        public ComputeAndTrackRouteFeedback(ushort last_node_id, ushort next_node_id, ushort current_edge_id, RouteMsg route, Nav.PathMsg path, string[] operations_triggered, bool rerouted)
        {
            this.last_node_id = last_node_id;
            this.next_node_id = next_node_id;
            this.current_edge_id = current_edge_id;
            this.route = route;
            this.path = path;
            this.operations_triggered = operations_triggered;
            this.rerouted = rerouted;
        }

        public static ComputeAndTrackRouteFeedback Deserialize(MessageDeserializer deserializer) => new ComputeAndTrackRouteFeedback(deserializer);

        private ComputeAndTrackRouteFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.last_node_id);
            deserializer.Read(out this.next_node_id);
            deserializer.Read(out this.current_edge_id);
            this.route = RouteMsg.Deserialize(deserializer);
            this.path = Nav.PathMsg.Deserialize(deserializer);
            deserializer.Read(out this.operations_triggered, deserializer.ReadLength());
            deserializer.Read(out this.rerouted);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.last_node_id);
            serializer.Write(this.next_node_id);
            serializer.Write(this.current_edge_id);
            serializer.Write(this.route);
            serializer.Write(this.path);
            serializer.WriteLength(this.operations_triggered);
            serializer.Write(this.operations_triggered);
            serializer.Write(this.rerouted);
        }

        public override string ToString()
        {
            return "ComputeAndTrackRouteFeedback: " +
            "\nlast_node_id: " + last_node_id.ToString() +
            "\nnext_node_id: " + next_node_id.ToString() +
            "\ncurrent_edge_id: " + current_edge_id.ToString() +
            "\nroute: " + route.ToString() +
            "\npath: " + path.ToString() +
            "\noperations_triggered: " + System.String.Join(", ", operations_triggered.ToList()) +
            "\nrerouted: " + rerouted.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
