//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputeRouteResult : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputeRoute";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        //  Error codes
        public const ushort NONE = 0;
        public const ushort UNKNOWN = 400;
        public const ushort TF_ERROR = 401;
        public const ushort NO_VALID_GRAPH = 402;
        public const ushort INDETERMINANT_NODES_ON_GRAPH = 403;
        public const ushort TIMEOUT = 404;
        public const ushort NO_VALID_ROUTE = 405;
        public const ushort INVALID_EDGE_SCORER_USE = 407;
        public BuiltinInterfaces.DurationMsg planning_time;
        public Nav.PathMsg path;
        public RouteMsg route;

        public ComputeRouteResult()
        {
            this.planning_time = new BuiltinInterfaces.DurationMsg();
            this.path = new Nav.PathMsg();
            this.route = new RouteMsg();
        }

        public ComputeRouteResult(BuiltinInterfaces.DurationMsg planning_time, Nav.PathMsg path, RouteMsg route)
        {
            this.planning_time = planning_time;
            this.path = path;
            this.route = route;
        }

        public static ComputeRouteResult Deserialize(MessageDeserializer deserializer) => new ComputeRouteResult(deserializer);

        private ComputeRouteResult(MessageDeserializer deserializer)
        {
            this.planning_time = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
            this.path = Nav.PathMsg.Deserialize(deserializer);
            this.route = RouteMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.planning_time);
            serializer.Write(this.path);
            serializer.Write(this.route);
        }

        public override string ToString()
        {
            return "ComputeRouteResult: " +
            "\nplanning_time: " + planning_time.ToString() +
            "\npath: " + path.ToString() +
            "\nroute: " + route.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
