//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputePathToPoseGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputePathToPose";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Geometry.PoseStampedMsg goal;
        public Geometry.PoseStampedMsg start;
        public string planner_id;
        public bool use_start;
        //  If false, use current robot pose as path start, if true, use start above instead

        public ComputePathToPoseGoal()
        {
            this.goal = new Geometry.PoseStampedMsg();
            this.start = new Geometry.PoseStampedMsg();
            this.planner_id = "";
            this.use_start = false;
        }

        public ComputePathToPoseGoal(Geometry.PoseStampedMsg goal, Geometry.PoseStampedMsg start, string planner_id, bool use_start)
        {
            this.goal = goal;
            this.start = start;
            this.planner_id = planner_id;
            this.use_start = use_start;
        }

        public static ComputePathToPoseGoal Deserialize(MessageDeserializer deserializer) => new ComputePathToPoseGoal(deserializer);

        private ComputePathToPoseGoal(MessageDeserializer deserializer)
        {
            this.goal = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.start = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.planner_id);
            deserializer.Read(out this.use_start);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.goal);
            serializer.Write(this.start);
            serializer.Write(this.planner_id);
            serializer.Write(this.use_start);
        }

        public override string ToString()
        {
            return "ComputePathToPoseGoal: " +
            "\ngoal: " + goal.ToString() +
            "\nstart: " + start.ToString() +
            "\nplanner_id: " + planner_id.ToString() +
            "\nuse_start: " + use_start.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
