//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ComputeAndTrackRouteGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ComputeAndTrackRoute";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public ushort start_id;
        public Geometry.PoseStampedMsg start;
        public ushort goal_id;
        public Geometry.PoseStampedMsg goal;
        public bool use_start;
        //  Whether to use the start field or find the start pose in TF
        public bool use_poses;
        //  Whether to use the poses or the IDs fields for request

        public ComputeAndTrackRouteGoal()
        {
            this.start_id = 0;
            this.start = new Geometry.PoseStampedMsg();
            this.goal_id = 0;
            this.goal = new Geometry.PoseStampedMsg();
            this.use_start = false;
            this.use_poses = false;
        }

        public ComputeAndTrackRouteGoal(ushort start_id, Geometry.PoseStampedMsg start, ushort goal_id, Geometry.PoseStampedMsg goal, bool use_start, bool use_poses)
        {
            this.start_id = start_id;
            this.start = start;
            this.goal_id = goal_id;
            this.goal = goal;
            this.use_start = use_start;
            this.use_poses = use_poses;
        }

        public static ComputeAndTrackRouteGoal Deserialize(MessageDeserializer deserializer) => new ComputeAndTrackRouteGoal(deserializer);

        private ComputeAndTrackRouteGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start_id);
            this.start = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.goal_id);
            this.goal = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.use_start);
            deserializer.Read(out this.use_poses);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start_id);
            serializer.Write(this.start);
            serializer.Write(this.goal_id);
            serializer.Write(this.goal);
            serializer.Write(this.use_start);
            serializer.Write(this.use_poses);
        }

        public override string ToString()
        {
            return "ComputeAndTrackRouteGoal: " +
            "\nstart_id: " + start_id.ToString() +
            "\nstart: " + start.ToString() +
            "\ngoal_id: " + goal_id.ToString() +
            "\ngoal: " + goal.ToString() +
            "\nuse_start: " + use_start.ToString() +
            "\nuse_poses: " + use_poses.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
