//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class DriveOnHeadingResult : Message
    {
        public const string k_RosMessageName = "nav2_msgs/DriveOnHeading";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        public BuiltinInterfaces.DurationMsg total_elapsed_time;

        public DriveOnHeadingResult()
        {
            this.total_elapsed_time = new BuiltinInterfaces.DurationMsg();
        }

        public DriveOnHeadingResult(BuiltinInterfaces.DurationMsg total_elapsed_time)
        {
            this.total_elapsed_time = total_elapsed_time;
        }

        public static DriveOnHeadingResult Deserialize(MessageDeserializer deserializer) => new DriveOnHeadingResult(deserializer);

        private DriveOnHeadingResult(MessageDeserializer deserializer)
        {
            this.total_elapsed_time = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.total_elapsed_time);
        }

        public override string ToString()
        {
            return "DriveOnHeadingResult: " +
            "\ntotal_elapsed_time: " + total_elapsed_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
