//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class DummyBehaviorGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/DummyBehavior";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Std.StringMsg command;

        public DummyBehaviorGoal()
        {
            this.command = new Std.StringMsg();
        }

        public DummyBehaviorGoal(Std.StringMsg command)
        {
            this.command = command;
        }

        public static DummyBehaviorGoal Deserialize(MessageDeserializer deserializer) => new DummyBehaviorGoal(deserializer);

        private DummyBehaviorGoal(MessageDeserializer deserializer)
        {
            this.command = Std.StringMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
        }

        public override string ToString()
        {
            return "DummyBehaviorGoal: " +
            "\ncommand: " + command.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
