//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class FollowPathGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/FollowPath";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Nav.PathMsg path;
        public string controller_id;
        public string goal_checker_id;

        public FollowPathGoal()
        {
            this.path = new Nav.PathMsg();
            this.controller_id = "";
            this.goal_checker_id = "";
        }

        public FollowPathGoal(Nav.PathMsg path, string controller_id, string goal_checker_id)
        {
            this.path = path;
            this.controller_id = controller_id;
            this.goal_checker_id = goal_checker_id;
        }

        public static FollowPathGoal Deserialize(MessageDeserializer deserializer) => new FollowPathGoal(deserializer);

        private FollowPathGoal(MessageDeserializer deserializer)
        {
            this.path = Nav.PathMsg.Deserialize(deserializer);
            deserializer.Read(out this.controller_id);
            deserializer.Read(out this.goal_checker_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.path);
            serializer.Write(this.controller_id);
            serializer.Write(this.goal_checker_id);
        }

        public override string ToString()
        {
            return "FollowPathGoal: " +
            "\npath: " + path.ToString() +
            "\ncontroller_id: " + controller_id.ToString() +
            "\ngoal_checker_id: " + goal_checker_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
