//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class FollowWaypointsResult : Message
    {
        public const string k_RosMessageName = "nav2_msgs/FollowWaypoints";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        public int[] missed_waypoints;

        public FollowWaypointsResult()
        {
            this.missed_waypoints = new int[0];
        }

        public FollowWaypointsResult(int[] missed_waypoints)
        {
            this.missed_waypoints = missed_waypoints;
        }

        public static FollowWaypointsResult Deserialize(MessageDeserializer deserializer) => new FollowWaypointsResult(deserializer);

        private FollowWaypointsResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.missed_waypoints, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.missed_waypoints);
            serializer.Write(this.missed_waypoints);
        }

        public override string ToString()
        {
            return "FollowWaypointsResult: " +
            "\nmissed_waypoints: " + System.String.Join(", ", missed_waypoints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
