//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class FollowPathFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/FollowPath";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition
        public float distance_to_goal;
        public float speed;

        public FollowPathFeedback()
        {
            this.distance_to_goal = 0.0f;
            this.speed = 0.0f;
        }

        public FollowPathFeedback(float distance_to_goal, float speed)
        {
            this.distance_to_goal = distance_to_goal;
            this.speed = speed;
        }

        public static FollowPathFeedback Deserialize(MessageDeserializer deserializer) => new FollowPathFeedback(deserializer);

        private FollowPathFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance_to_goal);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.distance_to_goal);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "FollowPathFeedback: " +
            "\ndistance_to_goal: " + distance_to_goal.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
