//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class FollowWaypointsFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/FollowWaypoints";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition
        public uint current_waypoint;

        public FollowWaypointsFeedback()
        {
            this.current_waypoint = 0;
        }

        public FollowWaypointsFeedback(uint current_waypoint)
        {
            this.current_waypoint = current_waypoint;
        }

        public static FollowWaypointsFeedback Deserialize(MessageDeserializer deserializer) => new FollowWaypointsFeedback(deserializer);

        private FollowWaypointsFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_waypoint);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_waypoint);
        }

        public override string ToString()
        {
            return "FollowWaypointsFeedback: " +
            "\ncurrent_waypoint: " + current_waypoint.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
