//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class FollowWaypointsGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/FollowWaypoints";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Geometry.PoseStampedMsg[] poses;

        public FollowWaypointsGoal()
        {
            this.poses = new Geometry.PoseStampedMsg[0];
        }

        public FollowWaypointsGoal(Geometry.PoseStampedMsg[] poses)
        {
            this.poses = poses;
        }

        public static FollowWaypointsGoal Deserialize(MessageDeserializer deserializer) => new FollowWaypointsGoal(deserializer);

        private FollowWaypointsGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.poses, Geometry.PoseStampedMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
        }

        public override string ToString()
        {
            return "FollowWaypointsGoal: " +
            "\nposes: " + System.String.Join(", ", poses.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
