//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class NavigateThroughPosesGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/NavigateThroughPoses";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Geometry.PoseStampedMsg[] poses;
        public string behavior_tree;

        public NavigateThroughPosesGoal()
        {
            this.poses = new Geometry.PoseStampedMsg[0];
            this.behavior_tree = "";
        }

        public NavigateThroughPosesGoal(Geometry.PoseStampedMsg[] poses, string behavior_tree)
        {
            this.poses = poses;
            this.behavior_tree = behavior_tree;
        }

        public static NavigateThroughPosesGoal Deserialize(MessageDeserializer deserializer) => new NavigateThroughPosesGoal(deserializer);

        private NavigateThroughPosesGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.poses, Geometry.PoseStampedMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.behavior_tree);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.poses);
            serializer.Write(this.poses);
            serializer.Write(this.behavior_tree);
        }

        public override string ToString()
        {
            return "NavigateThroughPosesGoal: " +
            "\nposes: " + System.String.Join(", ", poses.ToList()) +
            "\nbehavior_tree: " + behavior_tree.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
