//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class NavigateToPoseGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/NavigateToPose";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Geometry.PoseStampedMsg pose;
        public string behavior_tree;

        public NavigateToPoseGoal()
        {
            this.pose = new Geometry.PoseStampedMsg();
            this.behavior_tree = "";
        }

        public NavigateToPoseGoal(Geometry.PoseStampedMsg pose, string behavior_tree)
        {
            this.pose = pose;
            this.behavior_tree = behavior_tree;
        }

        public static NavigateToPoseGoal Deserialize(MessageDeserializer deserializer) => new NavigateToPoseGoal(deserializer);

        private NavigateToPoseGoal(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.behavior_tree);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.behavior_tree);
        }

        public override string ToString()
        {
            return "NavigateToPoseGoal: " +
            "\npose: " + pose.ToString() +
            "\nbehavior_tree: " + behavior_tree.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
