//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class NavigateThroughPosesFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/NavigateThroughPoses";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition
        public Geometry.PoseStampedMsg current_pose;
        public BuiltinInterfaces.DurationMsg navigation_time;
        public BuiltinInterfaces.DurationMsg estimated_time_remaining;
        public short number_of_recoveries;
        public float distance_remaining;
        public short number_of_poses_remaining;

        public NavigateThroughPosesFeedback()
        {
            this.current_pose = new Geometry.PoseStampedMsg();
            this.navigation_time = new BuiltinInterfaces.DurationMsg();
            this.estimated_time_remaining = new BuiltinInterfaces.DurationMsg();
            this.number_of_recoveries = 0;
            this.distance_remaining = 0.0f;
            this.number_of_poses_remaining = 0;
        }

        public NavigateThroughPosesFeedback(Geometry.PoseStampedMsg current_pose, BuiltinInterfaces.DurationMsg navigation_time, BuiltinInterfaces.DurationMsg estimated_time_remaining, short number_of_recoveries, float distance_remaining, short number_of_poses_remaining)
        {
            this.current_pose = current_pose;
            this.navigation_time = navigation_time;
            this.estimated_time_remaining = estimated_time_remaining;
            this.number_of_recoveries = number_of_recoveries;
            this.distance_remaining = distance_remaining;
            this.number_of_poses_remaining = number_of_poses_remaining;
        }

        public static NavigateThroughPosesFeedback Deserialize(MessageDeserializer deserializer) => new NavigateThroughPosesFeedback(deserializer);

        private NavigateThroughPosesFeedback(MessageDeserializer deserializer)
        {
            this.current_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            this.navigation_time = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
            this.estimated_time_remaining = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.number_of_recoveries);
            deserializer.Read(out this.distance_remaining);
            deserializer.Read(out this.number_of_poses_remaining);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_pose);
            serializer.Write(this.navigation_time);
            serializer.Write(this.estimated_time_remaining);
            serializer.Write(this.number_of_recoveries);
            serializer.Write(this.distance_remaining);
            serializer.Write(this.number_of_poses_remaining);
        }

        public override string ToString()
        {
            return "NavigateThroughPosesFeedback: " +
            "\ncurrent_pose: " + current_pose.ToString() +
            "\nnavigation_time: " + navigation_time.ToString() +
            "\nestimated_time_remaining: " + estimated_time_remaining.ToString() +
            "\nnumber_of_recoveries: " + number_of_recoveries.ToString() +
            "\ndistance_remaining: " + distance_remaining.ToString() +
            "\nnumber_of_poses_remaining: " + number_of_poses_remaining.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
