//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class NavigateThroughPosesResult : Message
    {
        public const string k_RosMessageName = "nav2_msgs/NavigateThroughPoses";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        public Std.EmptyMsg result;

        public NavigateThroughPosesResult()
        {
            this.result = new Std.EmptyMsg();
        }

        public NavigateThroughPosesResult(Std.EmptyMsg result)
        {
            this.result = result;
        }

        public static NavigateThroughPosesResult Deserialize(MessageDeserializer deserializer) => new NavigateThroughPosesResult(deserializer);

        private NavigateThroughPosesResult(MessageDeserializer deserializer)
        {
            this.result = Std.EmptyMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "NavigateThroughPosesResult: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
