//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class SmoothPathResult : Message
    {
        public const string k_RosMessageName = "nav2_msgs/SmoothPath";
        public override string RosMessageName => k_RosMessageName;

        // result definition
        public Nav.PathMsg path;
        public BuiltinInterfaces.DurationMsg smoothing_duration;
        public bool was_completed;

        public SmoothPathResult()
        {
            this.path = new Nav.PathMsg();
            this.smoothing_duration = new BuiltinInterfaces.DurationMsg();
            this.was_completed = false;
        }

        public SmoothPathResult(Nav.PathMsg path, BuiltinInterfaces.DurationMsg smoothing_duration, bool was_completed)
        {
            this.path = path;
            this.smoothing_duration = smoothing_duration;
            this.was_completed = was_completed;
        }

        public static SmoothPathResult Deserialize(MessageDeserializer deserializer) => new SmoothPathResult(deserializer);

        private SmoothPathResult(MessageDeserializer deserializer)
        {
            this.path = Nav.PathMsg.Deserialize(deserializer);
            this.smoothing_duration = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.was_completed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.path);
            serializer.Write(this.smoothing_duration);
            serializer.Write(this.was_completed);
        }

        public override string ToString()
        {
            return "SmoothPathResult: " +
            "\npath: " + path.ToString() +
            "\nsmoothing_duration: " + smoothing_duration.ToString() +
            "\nwas_completed: " + was_completed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
