//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class SmoothPathGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/SmoothPath";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public Nav.PathMsg path;
        public string smoother_id;
        public BuiltinInterfaces.DurationMsg max_smoothing_duration;
        public bool check_for_collisions;

        public SmoothPathGoal()
        {
            this.path = new Nav.PathMsg();
            this.smoother_id = "";
            this.max_smoothing_duration = new BuiltinInterfaces.DurationMsg();
            this.check_for_collisions = false;
        }

        public SmoothPathGoal(Nav.PathMsg path, string smoother_id, BuiltinInterfaces.DurationMsg max_smoothing_duration, bool check_for_collisions)
        {
            this.path = path;
            this.smoother_id = smoother_id;
            this.max_smoothing_duration = max_smoothing_duration;
            this.check_for_collisions = check_for_collisions;
        }

        public static SmoothPathGoal Deserialize(MessageDeserializer deserializer) => new SmoothPathGoal(deserializer);

        private SmoothPathGoal(MessageDeserializer deserializer)
        {
            this.path = Nav.PathMsg.Deserialize(deserializer);
            deserializer.Read(out this.smoother_id);
            this.max_smoothing_duration = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.check_for_collisions);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.path);
            serializer.Write(this.smoother_id);
            serializer.Write(this.max_smoothing_duration);
            serializer.Write(this.check_for_collisions);
        }

        public override string ToString()
        {
            return "SmoothPathGoal: " +
            "\npath: " + path.ToString() +
            "\nsmoother_id: " + smoother_id.ToString() +
            "\nmax_smoothing_duration: " + max_smoothing_duration.ToString() +
            "\ncheck_for_collisions: " + check_for_collisions.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
