//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class SpinFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/Spin";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition
        public float angular_distance_traveled;

        public SpinFeedback()
        {
            this.angular_distance_traveled = 0.0f;
        }

        public SpinFeedback(float angular_distance_traveled)
        {
            this.angular_distance_traveled = angular_distance_traveled;
        }

        public static SpinFeedback Deserialize(MessageDeserializer deserializer) => new SpinFeedback(deserializer);

        private SpinFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angular_distance_traveled);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angular_distance_traveled);
        }

        public override string ToString()
        {
            return "SpinFeedback: " +
            "\nangular_distance_traveled: " + angular_distance_traveled.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
