//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class SpinGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/Spin";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public float target_yaw;
        public BuiltinInterfaces.DurationMsg time_allowance;

        public SpinGoal()
        {
            this.target_yaw = 0.0f;
            this.time_allowance = new BuiltinInterfaces.DurationMsg();
        }

        public SpinGoal(float target_yaw, BuiltinInterfaces.DurationMsg time_allowance)
        {
            this.target_yaw = target_yaw;
            this.time_allowance = time_allowance;
        }

        public static SpinGoal Deserialize(MessageDeserializer deserializer) => new SpinGoal(deserializer);

        private SpinGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target_yaw);
            this.time_allowance = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_yaw);
            serializer.Write(this.time_allowance);
        }

        public override string ToString()
        {
            return "SpinGoal: " +
            "\ntarget_yaw: " + target_yaw.ToString() +
            "\ntime_allowance: " + time_allowance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
