//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class WaitGoal : Message
    {
        public const string k_RosMessageName = "nav2_msgs/Wait";
        public override string RosMessageName => k_RosMessageName;

        // goal definition
        public BuiltinInterfaces.DurationMsg time;

        public WaitGoal()
        {
            this.time = new BuiltinInterfaces.DurationMsg();
        }

        public WaitGoal(BuiltinInterfaces.DurationMsg time)
        {
            this.time = time;
        }

        public static WaitGoal Deserialize(MessageDeserializer deserializer) => new WaitGoal(deserializer);

        private WaitGoal(MessageDeserializer deserializer)
        {
            this.time = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
        }

        public override string ToString()
        {
            return "WaitGoal: " +
            "\ntime: " + time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
