//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class WaitFeedback : Message
    {
        public const string k_RosMessageName = "nav2_msgs/Wait";
        public override string RosMessageName => k_RosMessageName;

        // feedback definition
        public BuiltinInterfaces.DurationMsg time_left;

        public WaitFeedback()
        {
            this.time_left = new BuiltinInterfaces.DurationMsg();
        }

        public WaitFeedback(BuiltinInterfaces.DurationMsg time_left)
        {
            this.time_left = time_left;
        }

        public static WaitFeedback Deserialize(MessageDeserializer deserializer) => new WaitFeedback(deserializer);

        private WaitFeedback(MessageDeserializer deserializer)
        {
            this.time_left = BuiltinInterfaces.DurationMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time_left);
        }

        public override string ToString()
        {
            return "WaitFeedback: " +
            "\ntime_left: " + time_left.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
