//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class BehaviorTreeStatusChangeMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/BehaviorTreeStatusChange";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        //  internal behavior tree event timestamp. Typically this is wall clock time
        public string node_name;
        public string previous_status;
        //  IDLE, RUNNING, SUCCESS or FAILURE
        public string current_status;
        //  IDLE, RUNNING, SUCCESS or FAILURE

        public BehaviorTreeStatusChangeMsg()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.node_name = "";
            this.previous_status = "";
            this.current_status = "";
        }

        public BehaviorTreeStatusChangeMsg(BuiltinInterfaces.TimeMsg timestamp, string node_name, string previous_status, string current_status)
        {
            this.timestamp = timestamp;
            this.node_name = node_name;
            this.previous_status = previous_status;
            this.current_status = current_status;
        }

        public static BehaviorTreeStatusChangeMsg Deserialize(MessageDeserializer deserializer) => new BehaviorTreeStatusChangeMsg(deserializer);

        private BehaviorTreeStatusChangeMsg(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.node_name);
            deserializer.Read(out this.previous_status);
            deserializer.Read(out this.current_status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.node_name);
            serializer.Write(this.previous_status);
            serializer.Write(this.current_status);
        }

        public override string ToString()
        {
            return "BehaviorTreeStatusChangeMsg: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nnode_name: " + node_name.ToString() +
            "\nprevious_status: " + previous_status.ToString() +
            "\ncurrent_status: " + current_status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
