//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class BehaviorTreeLogMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/BehaviorTreeLog";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg timestamp;
        //  ROS time that this log message was sent.
        public BehaviorTreeStatusChangeMsg[] event_log;

        public BehaviorTreeLogMsg()
        {
            this.timestamp = new BuiltinInterfaces.TimeMsg();
            this.event_log = new BehaviorTreeStatusChangeMsg[0];
        }

        public BehaviorTreeLogMsg(BuiltinInterfaces.TimeMsg timestamp, BehaviorTreeStatusChangeMsg[] event_log)
        {
            this.timestamp = timestamp;
            this.event_log = event_log;
        }

        public static BehaviorTreeLogMsg Deserialize(MessageDeserializer deserializer) => new BehaviorTreeLogMsg(deserializer);

        private BehaviorTreeLogMsg(MessageDeserializer deserializer)
        {
            this.timestamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.event_log, BehaviorTreeStatusChangeMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.WriteLength(this.event_log);
            serializer.Write(this.event_log);
        }

        public override string ToString()
        {
            return "BehaviorTreeLogMsg: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nevent_log: " + System.String.Join(", ", event_log.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
