//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class CollisionMonitorStateMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/CollisionMonitorState";
        public override string RosMessageName => k_RosMessageName;

        //  Action type for robot in Collision Monitor
        public const byte DO_NOTHING = 0; //  No action
        public const byte STOP = 1; //  Stop the robot
        public const byte SLOWDOWN = 2; //  Slowdown in percentage from current operating speed
        public const byte APPROACH = 3; //  Keep constant time interval before collision
        public byte action_type;
        //  Name of triggered polygon
        public string polygon_name;

        public CollisionMonitorStateMsg()
        {
            this.action_type = 0;
            this.polygon_name = "";
        }

        public CollisionMonitorStateMsg(byte action_type, string polygon_name)
        {
            this.action_type = action_type;
            this.polygon_name = polygon_name;
        }

        public static CollisionMonitorStateMsg Deserialize(MessageDeserializer deserializer) => new CollisionMonitorStateMsg(deserializer);

        private CollisionMonitorStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.action_type);
            deserializer.Read(out this.polygon_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_type);
            serializer.Write(this.polygon_name);
        }

        public override string ToString()
        {
            return "CollisionMonitorStateMsg: " +
            "\naction_type: " + action_type.ToString() +
            "\npolygon_name: " + polygon_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
