//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class CostmapMetaDataMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/CostmapMetaData";
        public override string RosMessageName => k_RosMessageName;

        //  This hold basic information about the characteristics of the Costmap
        //  The time at which the static map was loaded
        public BuiltinInterfaces.TimeMsg map_load_time;
        //  The time of the last update to costmap
        public BuiltinInterfaces.TimeMsg update_time;
        //  The corresponding layer name
        public string layer;
        //  The map resolution [m/cell]
        public float resolution;
        //  Number of cells in the horizontal direction
        public uint size_x;
        //  Number of cells in the vertical direction
        public uint size_y;
        //  The origin of the costmap [m, m, rad].
        //  This is the real-world pose of the cell (0,0) in the map.
        public Geometry.PoseMsg origin;

        public CostmapMetaDataMsg()
        {
            this.map_load_time = new BuiltinInterfaces.TimeMsg();
            this.update_time = new BuiltinInterfaces.TimeMsg();
            this.layer = "";
            this.resolution = 0.0f;
            this.size_x = 0;
            this.size_y = 0;
            this.origin = new Geometry.PoseMsg();
        }

        public CostmapMetaDataMsg(BuiltinInterfaces.TimeMsg map_load_time, BuiltinInterfaces.TimeMsg update_time, string layer, float resolution, uint size_x, uint size_y, Geometry.PoseMsg origin)
        {
            this.map_load_time = map_load_time;
            this.update_time = update_time;
            this.layer = layer;
            this.resolution = resolution;
            this.size_x = size_x;
            this.size_y = size_y;
            this.origin = origin;
        }

        public static CostmapMetaDataMsg Deserialize(MessageDeserializer deserializer) => new CostmapMetaDataMsg(deserializer);

        private CostmapMetaDataMsg(MessageDeserializer deserializer)
        {
            this.map_load_time = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            this.update_time = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.layer);
            deserializer.Read(out this.resolution);
            deserializer.Read(out this.size_x);
            deserializer.Read(out this.size_y);
            this.origin = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.map_load_time);
            serializer.Write(this.update_time);
            serializer.Write(this.layer);
            serializer.Write(this.resolution);
            serializer.Write(this.size_x);
            serializer.Write(this.size_y);
            serializer.Write(this.origin);
        }

        public override string ToString()
        {
            return "CostmapMetaDataMsg: " +
            "\nmap_load_time: " + map_load_time.ToString() +
            "\nupdate_time: " + update_time.ToString() +
            "\nlayer: " + layer.ToString() +
            "\nresolution: " + resolution.ToString() +
            "\nsize_x: " + size_x.ToString() +
            "\nsize_y: " + size_y.ToString() +
            "\norigin: " + origin.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
