//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class CostmapMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/Costmap";
        public override string RosMessageName => k_RosMessageName;

        //  This represents a 2-D grid map, in which each cell has an associated cost
        public Std.HeaderMsg header;
        //  MetaData for the map
        public CostmapMetaDataMsg metadata;
        //  The cost data, in row-major order, starting with (0,0).
        public byte[] data;

        public CostmapMsg()
        {
            this.header = new Std.HeaderMsg();
            this.metadata = new CostmapMetaDataMsg();
            this.data = new byte[0];
        }

        public CostmapMsg(Std.HeaderMsg header, CostmapMetaDataMsg metadata, byte[] data)
        {
            this.header = header;
            this.metadata = metadata;
            this.data = data;
        }

        public static CostmapMsg Deserialize(MessageDeserializer deserializer) => new CostmapMsg(deserializer);

        private CostmapMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.metadata = CostmapMetaDataMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.metadata);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "CostmapMsg: " +
            "\nheader: " + header.ToString() +
            "\nmetadata: " + metadata.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
