//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class CostmapFilterInfoMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/CostmapFilterInfo";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  Type of plugin used (keepout filter, speed limit in m/s, speed limit in percent, etc...)
        //  0: keepout/lanes filter
        //  1: speed limit filter in % of maximum speed
        //  2: speed limit filter in absolute values (m/s)
        public byte type;
        //  Name of filter mask topic
        public string filter_mask_topic;
        //  Multiplier base offset and multiplier coefficient for conversion of OccGrid.
        //  Used to convert OccupancyGrid data values to filter space values.
        //  data -> into some other number space:
        //  space = data * multiplier + base
        public float @base;
        public float multiplier;

        public CostmapFilterInfoMsg()
        {
            this.header = new Std.HeaderMsg();
            this.type = 0;
            this.filter_mask_topic = "";
            this.@base = 0.0f;
            this.multiplier = 0.0f;
        }

        public CostmapFilterInfoMsg(Std.HeaderMsg header, byte type, string filter_mask_topic, float @base, float multiplier)
        {
            this.header = header;
            this.type = type;
            this.filter_mask_topic = filter_mask_topic;
            this.@base = @base;
            this.multiplier = multiplier;
        }

        public static CostmapFilterInfoMsg Deserialize(MessageDeserializer deserializer) => new CostmapFilterInfoMsg(deserializer);

        private CostmapFilterInfoMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.type);
            deserializer.Read(out this.filter_mask_topic);
            deserializer.Read(out this.@base);
            deserializer.Read(out this.multiplier);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.type);
            serializer.Write(this.filter_mask_topic);
            serializer.Write(this.@base);
            serializer.Write(this.multiplier);
        }

        public override string ToString()
        {
            return "CostmapFilterInfoMsg: " +
            "\nheader: " + header.ToString() +
            "\ntype: " + type.ToString() +
            "\nfilter_mask_topic: " + filter_mask_topic.ToString() +
            "\n@base: " + @base.ToString() +
            "\nmultiplier: " + multiplier.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
