//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class EdgeCostMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/EdgeCost";
        public override string RosMessageName => k_RosMessageName;

        //  Edge cost to use with nav2_msgs/srv/DynamicEdges to adjust route edge costs
        public ushort edgeid;
        public float cost;

        public EdgeCostMsg()
        {
            this.edgeid = 0;
            this.cost = 0.0f;
        }

        public EdgeCostMsg(ushort edgeid, float cost)
        {
            this.edgeid = edgeid;
            this.cost = cost;
        }

        public static EdgeCostMsg Deserialize(MessageDeserializer deserializer) => new EdgeCostMsg(deserializer);

        private EdgeCostMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.edgeid);
            deserializer.Read(out this.cost);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.edgeid);
            serializer.Write(this.cost);
        }

        public override string ToString()
        {
            return "EdgeCostMsg: " +
            "\nedgeid: " + edgeid.ToString() +
            "\ncost: " + cost.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
