//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ParticleCloudMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/ParticleCloud";
        public override string RosMessageName => k_RosMessageName;

        //  This represents a particle cloud containing particle poses and weights
        public Std.HeaderMsg header;
        //  Array of particles in the cloud
        public ParticleMsg[] particles;

        public ParticleCloudMsg()
        {
            this.header = new Std.HeaderMsg();
            this.particles = new ParticleMsg[0];
        }

        public ParticleCloudMsg(Std.HeaderMsg header, ParticleMsg[] particles)
        {
            this.header = header;
            this.particles = particles;
        }

        public static ParticleCloudMsg Deserialize(MessageDeserializer deserializer) => new ParticleCloudMsg(deserializer);

        private ParticleCloudMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.particles, ParticleMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.particles);
            serializer.Write(this.particles);
        }

        public override string ToString()
        {
            return "ParticleCloudMsg: " +
            "\nheader: " + header.ToString() +
            "\nparticles: " + System.String.Join(", ", particles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
