//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class ParticleMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/Particle";
        public override string RosMessageName => k_RosMessageName;

        //  This represents an individual particle with weight produced by a particle filter
        public Geometry.PoseMsg pose;
        public double weight;

        public ParticleMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.weight = 0.0;
        }

        public ParticleMsg(Geometry.PoseMsg pose, double weight)
        {
            this.pose = pose;
            this.weight = weight;
        }

        public static ParticleMsg Deserialize(MessageDeserializer deserializer) => new ParticleMsg(deserializer);

        private ParticleMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.weight);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.weight);
        }

        public override string ToString()
        {
            return "ParticleMsg: " +
            "\npose: " + pose.ToString() +
            "\nweight: " + weight.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
