//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class RouteNodeMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/RouteNode";
        public override string RosMessageName => k_RosMessageName;

        public ushort nodeid;
        public Geometry.PointMsg position;

        public RouteNodeMsg()
        {
            this.nodeid = 0;
            this.position = new Geometry.PointMsg();
        }

        public RouteNodeMsg(ushort nodeid, Geometry.PointMsg position)
        {
            this.nodeid = nodeid;
            this.position = position;
        }

        public static RouteNodeMsg Deserialize(MessageDeserializer deserializer) => new RouteNodeMsg(deserializer);

        private RouteNodeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.nodeid);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.nodeid);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "RouteNodeMsg: " +
            "\nnodeid: " + nodeid.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
