//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class RouteEdgeMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/RouteEdge";
        public override string RosMessageName => k_RosMessageName;

        public ushort edgeid;
        public Geometry.PointMsg start;
        public Geometry.PointMsg end;

        public RouteEdgeMsg()
        {
            this.edgeid = 0;
            this.start = new Geometry.PointMsg();
            this.end = new Geometry.PointMsg();
        }

        public RouteEdgeMsg(ushort edgeid, Geometry.PointMsg start, Geometry.PointMsg end)
        {
            this.edgeid = edgeid;
            this.start = start;
            this.end = end;
        }

        public static RouteEdgeMsg Deserialize(MessageDeserializer deserializer) => new RouteEdgeMsg(deserializer);

        private RouteEdgeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.edgeid);
            this.start = Geometry.PointMsg.Deserialize(deserializer);
            this.end = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.edgeid);
            serializer.Write(this.start);
            serializer.Write(this.end);
        }

        public override string ToString()
        {
            return "RouteEdgeMsg: " +
            "\nedgeid: " + edgeid.ToString() +
            "\nstart: " + start.ToString() +
            "\nend: " + end.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
