//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class RouteMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/Route";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public float route_cost;
        public RouteNodeMsg[] nodes;
        //  ordered set of nodes of the route
        public RouteEdgeMsg[] edges;
        //  ordered set of edges that connect nodes

        public RouteMsg()
        {
            this.header = new Std.HeaderMsg();
            this.route_cost = 0.0f;
            this.nodes = new RouteNodeMsg[0];
            this.edges = new RouteEdgeMsg[0];
        }

        public RouteMsg(Std.HeaderMsg header, float route_cost, RouteNodeMsg[] nodes, RouteEdgeMsg[] edges)
        {
            this.header = header;
            this.route_cost = route_cost;
            this.nodes = nodes;
            this.edges = edges;
        }

        public static RouteMsg Deserialize(MessageDeserializer deserializer) => new RouteMsg(deserializer);

        private RouteMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.route_cost);
            deserializer.Read(out this.nodes, RouteNodeMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.edges, RouteEdgeMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.route_cost);
            serializer.WriteLength(this.nodes);
            serializer.Write(this.nodes);
            serializer.WriteLength(this.edges);
            serializer.Write(this.edges);
        }

        public override string ToString()
        {
            return "RouteMsg: " +
            "\nheader: " + header.ToString() +
            "\nroute_cost: " + route_cost.ToString() +
            "\nnodes: " + System.String.Join(", ", nodes.ToList()) +
            "\nedges: " + System.String.Join(", ", edges.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
