//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class SpeedLimitMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/SpeedLimit";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  Setting speed limit in percentage if true or in absolute values in false case
        public bool percentage;
        //  Maximum allowed speed (in percent of maximum robot speed or in m/s depending
        //  on "percentage" value). When no-limit it is set to 0.0
        public double speed_limit;

        public SpeedLimitMsg()
        {
            this.header = new Std.HeaderMsg();
            this.percentage = false;
            this.speed_limit = 0.0;
        }

        public SpeedLimitMsg(Std.HeaderMsg header, bool percentage, double speed_limit)
        {
            this.header = header;
            this.percentage = percentage;
            this.speed_limit = speed_limit;
        }

        public static SpeedLimitMsg Deserialize(MessageDeserializer deserializer) => new SpeedLimitMsg(deserializer);

        private SpeedLimitMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.percentage);
            deserializer.Read(out this.speed_limit);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.percentage);
            serializer.Write(this.speed_limit);
        }

        public override string ToString()
        {
            return "SpeedLimitMsg: " +
            "\nheader: " + header.ToString() +
            "\npercentage: " + percentage.ToString() +
            "\nspeed_limit: " + speed_limit.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
