//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Nav2
{
    [Serializable]
    public class VoxelGridMsg : Message
    {
        public const string k_RosMessageName = "nav2_msgs/VoxelGrid";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public uint[] data;
        public Geometry.Point32Msg origin;
        public Geometry.Vector3Msg resolutions;
        public uint size_x;
        public uint size_y;
        public uint size_z;

        public VoxelGridMsg()
        {
            this.header = new Std.HeaderMsg();
            this.data = new uint[0];
            this.origin = new Geometry.Point32Msg();
            this.resolutions = new Geometry.Vector3Msg();
            this.size_x = 0;
            this.size_y = 0;
            this.size_z = 0;
        }

        public VoxelGridMsg(Std.HeaderMsg header, uint[] data, Geometry.Point32Msg origin, Geometry.Vector3Msg resolutions, uint size_x, uint size_y, uint size_z)
        {
            this.header = header;
            this.data = data;
            this.origin = origin;
            this.resolutions = resolutions;
            this.size_x = size_x;
            this.size_y = size_y;
            this.size_z = size_z;
        }

        public static VoxelGridMsg Deserialize(MessageDeserializer deserializer) => new VoxelGridMsg(deserializer);

        private VoxelGridMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.data, sizeof(uint), deserializer.ReadLength());
            this.origin = Geometry.Point32Msg.Deserialize(deserializer);
            this.resolutions = Geometry.Vector3Msg.Deserialize(deserializer);
            deserializer.Read(out this.size_x);
            deserializer.Read(out this.size_y);
            deserializer.Read(out this.size_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
            serializer.Write(this.origin);
            serializer.Write(this.resolutions);
            serializer.Write(this.size_x);
            serializer.Write(this.size_y);
            serializer.Write(this.size_z);
        }

        public override string ToString()
        {
            return "VoxelGridMsg: " +
            "\nheader: " + header.ToString() +
            "\ndata: " + System.String.Join(", ", data.ToList()) +
            "\norigin: " + origin.ToString() +
            "\nresolutions: " + resolutions.ToString() +
            "\nsize_x: " + size_x.ToString() +
            "\nsize_y: " + size_y.ToString() +
            "\nsize_z: " + size_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
