//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Action
{
    [Serializable]
    public class CancelGoal_ResponseMsg : Message
    {
        public const string k_RosMessageName = "action_msgs/CancelGoal_Response";
        public override string RosMessageName => k_RosMessageName;

        // #
        // # Return codes.
        // #
        //  Indicates the request was accepted without any errors.
        // 
        //  One or more goals have transitioned to the CANCELING state. The
        //  goals_canceling list is not empty.
        public const sbyte ERROR_NONE = 0;
        //  Indicates the request was rejected.
        // 
        //  No goals have transitioned to the CANCELING state. The goals_canceling list is
        //  empty.
        public const sbyte ERROR_REJECTED = 1;
        //  Indicates the requested goal ID does not exist.
        // 
        //  No goals have transitioned to the CANCELING state. The goals_canceling list is
        //  empty.
        public const sbyte ERROR_UNKNOWN_GOAL_ID = 2;
        //  Indicates the goal is not cancelable because it is already in a terminal state.
        // 
        //  No goals have transitioned to the CANCELING state. The goals_canceling list is
        //  empty.
        public const sbyte ERROR_GOAL_TERMINATED = 3;
        //  Return code, see above definitions.
        public sbyte return_code;
        //  Goals that accepted the cancel request.
        public GoalInfoMsg[] goals_canceling;

        public CancelGoal_ResponseMsg()
        {
            this.return_code = 0;
            this.goals_canceling = new GoalInfoMsg[0];
        }

        public CancelGoal_ResponseMsg(sbyte return_code, GoalInfoMsg[] goals_canceling)
        {
            this.return_code = return_code;
            this.goals_canceling = goals_canceling;
        }

        public static CancelGoal_ResponseMsg Deserialize(MessageDeserializer deserializer) => new CancelGoal_ResponseMsg(deserializer);

        private CancelGoal_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.return_code);
            deserializer.Read(out this.goals_canceling, GoalInfoMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.return_code);
            serializer.WriteLength(this.goals_canceling);
            serializer.Write(this.goals_canceling);
        }

        public override string ToString()
        {
            return "CancelGoal_ResponseMsg: " +
            "\nreturn_code: " + return_code.ToString() +
            "\ngoals_canceling: " + System.String.Join(", ", goals_canceling.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
